#%RAML 1.0 Library
traits:
  clientHeader:
    headers:
      client_id:
        description: header client_id
        type: string
        example: 42b088a5-0780-4935-8b4c-033b8d625e82
      client_secret:
        description: header client_secret
        type: string
        example: CqMao7Z~BUm0_eWe1SVvOGs5v5~R9E8~_e
usage:
securitySchemes: 
  oauth2:
    description: OAuth 2.0 for authenticating all API requests.
    type: OAuth 2.0
    describedBy:
      headers:
        Authorization:
          description: |
             Used to send a valid OAuth 2 access token
          type: string
          example: bearer T42mKm3KHPhICr8KljfCzZ2EsI7_YWKTp07LYankMr6HEysETr5tfnw68E7Rd9SECouTiSfCMr5MxoGQs-WG0g
      responses:        
        401:
          description: Bad or expired token. To fix request a new access token
          headers:
            Content-Type:
              description: Header example 
              example: application/json
          body:
            application/json:  
              example: |
                {"error": "550e8400-e29b-41d4-a716-446655440000"}
        
        403:
          description: The provided access token doesn't have access to this resourcee.
          headers:
            Content-Type:
              description: sss
              example: application/json
          body:
            application/json:
               example: |
                  {"error": "testserror"}
    settings:
      authorizationUri: https://api_urlToken.com/oauth2/authorize
      accessTokenUri: https://api_urlAccess.com/oauth2/token
      authorizationGrants: [client_credentials]
