#%RAML 1.0 DataType
description: Response Payload All Characters Starwars
displayName: Response

properties:
  name:
    type: string
    required: true
  height:
    type: number
    required: true
  mass:
    type: number
    required: true
  hair_color:
    type: string
    required: true
  sking_color:
    type: string
    required: true
  eye_color:
    type: string
    required: true
  birth_year:
    type: string
    required: true
  gender:
    type: string
    required: true
additionalProperties: true