http:
 listener:
  port: "8081"

token:
  latitude: "20.270460"
  transactionId: "fs9999c7q86c33cdfd55"
  dateRequest: "2024-09-06T14:45:12.345Z"
  longitude: "-99.985171"

base:
  path: "/v1/api"
   
general:
  path: "/api/*"
  apiId: "18968478"
  
starwars:
 protocol: "HTTPS" 
 host: "swapi.dev"
 path: "/api/people"

timeoutRq: "90000"

partyIdentify:
  host: "nonprod.coppel.space"
  basePath: "/party-identity/oauth2/v1"
  path: "/validate"
  